# Generated by Django 2.1 on 2018-10-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_publicnetwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='jira_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='oauth_secret',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='oauth_token',
        ),
    ]
