# Generated by Django 2.1 on 2018-10-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='jira_issue_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='jira_issue_status',
        ),
    ]
