# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_changeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='changeid',
            field=models.TextField(default='no change ID'),
        ),

        migrations.AlterField(
            model_name='booking',
            name='changeid',
            field=models.TextField(blank=True, default='no change ID', null=True),
        ),
    ]
