# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180108_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ext_count',
            field=models.IntegerField(default=2),
        ),
    ]
