##############################################################################
# Copyright (c) 2018 Sawyer Bergeron and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('booking', '0004_auto_20180227_2136'), ('booking', '0005_auto_20180302_1719')]

    dependencies = [
        ('booking', '0003_auto_20180108_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='sup_scenarios',
            field=models.ManyToManyField(blank=True, to='booking.Scenario'),
        ),
        migrations.AddField(
            model_name='opsys',
            name='sup_installers',
            field=models.ManyToManyField(blank=True, to='booking.Installer'),
        ),
    ]
