# Generated by Django 2.1 on 2019-02-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0006_auto_20190124_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericinterface',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_inventory.InterfaceProfile'),
        ),
    ]
