# Generated by Django 2.1 on 2019-04-23 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0009_auto_20190315_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostOPNFVConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='hostconfiguration',
            name='opnfvRole',
        ),
        migrations.AddField(
            model_name='hostconfiguration',
            name='is_head_node',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostopnfvconfig',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_opnfv_config', to='resource_inventory.HostConfiguration'),
        ),
        migrations.AddField(
            model_name='hostopnfvconfig',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_opnfv_configs', to='resource_inventory.OPNFVRole'),
        ),
    ]
