# Generated by Django 2.1 on 2019-04-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_inventory', '0010_auto_20190423_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='opnfvconfig',
            name='description',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='opnfvconfig',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
