# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifier',
            old_name='msg_type_str',
            new_name='msg_type',
        ),
    ]
