# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20171215_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='msg_type',
            field=models.CharField(choices=[('email', 'Email'), ('webnotification', 'Web Notification')], default='email', max_length=240),
        ),
    ]
