# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_auto_20171215_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifier',
            old_name='msg_type',
            new_name='message_type',
        ),
    ]
